use super::*;
use crate::{
    Land,
    site::{
        generation::{place_circular_as_vec, spiral_staircase},
        util::sprites::PainterSpriteExt,
    },
    util::{CARDINALS, DIAGONALS, RandomField, Sampler},
};
use common::terrain::{BlockKind, SpriteKind, sprite::Owned};
use rand::prelude::*;
use std::{f32::consts::TAU, sync::Arc};
use vek::*;

/// Represents house data generated by the `generate()` method
pub struct SavannahGuardHut {
    /// Tile position of the door tile
    pub door_tile: Vec2<i32>,
    /// Axis aligned bounding region for the house
    bounds: Aabr<i32>,
    /// Approximate altitude of the door tile
    pub(crate) alt: i32,
}

impl SavannahGuardHut {
    pub fn generate(
        land: &Land,
        _rng: &mut impl Rng,
        site: &Site,
        door_tile: Vec2<i32>,
        door_dir: Vec2<i32>,
        tile_aabr: Aabr<i32>,
        alt: Option<i32>,
    ) -> Self {
        let door_tile_pos = site.tile_center_wpos(door_tile);
        let bounds = Aabr {
            min: site.tile_wpos(tile_aabr.min),
            max: site.tile_wpos(tile_aabr.max),
        };
        Self {
            bounds,
            door_tile: door_tile_pos,
            alt: alt.unwrap_or_else(|| {
                land.get_alt_approx(site.tile_center_wpos(door_tile + door_dir)) as i32
            }) + 2,
        }
    }
}

impl Structure for SavannahGuardHut {
    #[cfg(feature = "use-dyn-lib")]
    const UPDATE_FN: &'static [u8] = b"render_savannahhut\0";

    #[cfg_attr(feature = "be-dyn-lib", unsafe(export_name = "render_savannahhut"))]
    fn render_inner(&self, _site: &Site, _land: &Land, painter: &Painter) {
        let reed = Fill::Brick(BlockKind::Misc, Rgb::new(72, 55, 46), 22);
        let reed2 = Fill::Brick(BlockKind::Misc, Rgb::new(100, 77, 64), 22);
        let clay = Fill::Brick(BlockKind::Rock, Rgb::new(209, 124, 57), 22);
        let wood_dark = Fill::Brick(BlockKind::Wood, Rgb::new(142, 67, 27), 12);
        let color = Fill::Sampling(Arc::new(|center| {
            Some(match (RandomField::new(0).get(center)) % 7 {
                0 => Block::new(BlockKind::GlowingRock, Rgb::new(153, 82, 40)),
                1 => Block::new(BlockKind::GlowingRock, Rgb::new(172, 104, 57)),
                2 => Block::new(BlockKind::GlowingRock, Rgb::new(135, 106, 100)),
                3 => Block::new(BlockKind::GlowingRock, Rgb::new(198, 164, 139)),
                4 => Block::new(BlockKind::GlowingRock, Rgb::new(168, 163, 157)),
                5 => Block::new(BlockKind::GlowingRock, Rgb::new(73, 53, 42)),
                _ => Block::new(BlockKind::GlowingRock, Rgb::new(178, 124, 90)),
            })
        }));
        let sprite_fill = Fill::Sampling(Arc::new(|wpos| {
            Some(match (RandomField::new(0).get(wpos)) % 50 {
                0 => Block::air(SpriteKind::Bowl).with_attr(Owned(true)).unwrap(),
                1 => Block::air(SpriteKind::VialEmpty)
                    .with_attr(Owned(true))
                    .unwrap(),
                2 => Block::air(SpriteKind::Lantern),
                3 => Block::air(SpriteKind::JugArabic),
                4 => Block::air(SpriteKind::Crate)
                    .with_attr(Owned(true))
                    .unwrap(),
                _ => Block::new(BlockKind::Air, Rgb::new(0, 0, 0)),
            })
        }));

        let base = self.alt + 1;
        let center = self.bounds.center();
        let platform_height = 3;

        let length = (7 + RandomField::new(0).get(center.with_z(base)) % 2) as i32;
        let height = 2 * (length + 3) / 3;
        let radius = length + (length / 3);
        let reed_var = (1 + RandomField::new(0).get(center.with_z(base)) % 4) as f32;
        let reed_parts = 36_f32 + reed_var;
        let phi = TAU / reed_parts;

        // roof cone
        painter
            .cone(Aabb {
                min: (center - radius - 1)
                    .with_z(base + platform_height + height - (height / 2) + 2),
                max: (center + radius + 1)
                    .with_z(base + platform_height + height + (height / 2) + reed_var as i32),
            })
            .fill(reed.clone());
        painter
            .cone(Aabb {
                min: (center - radius - 1)
                    .with_z(base + platform_height + height - (height / 2) + 1),
                max: (center + radius + 1)
                    .with_z(base + platform_height + height + (height / 2) - 1 + reed_var as i32),
            })
            .clear();

        // reed roof lines
        for n in 1..=reed_parts as i32 {
            let pos = Vec2::new(
                center.x + ((radius as f32) * ((n as f32 * phi).cos())) as i32,
                center.y + ((radius as f32) * ((n as f32 * phi).sin())) as i32,
            );
            painter
                .line(
                    pos.with_z(base + platform_height + height - (height / 2) + 1),
                    center.with_z(
                        base + platform_height + height + (height / 2) + 1 + reed_var as i32,
                    ),
                    1.0,
                )
                .fill(reed.clone());
        }

        // room
        let room = painter.cylinder(Aabb {
            min: (center - (radius - 3)).with_z(base + platform_height),
            max: (center + (radius - 3) + 1).with_z(base + platform_height + height),
        });
        room.fill(clay.clone());

        // decor inlays
        for dir in DIAGONALS {
            let decor_pos = center + dir * (length - 1);
            let decor = painter
                .line(
                    center.with_z(base + platform_height + 3),
                    decor_pos.with_z(base + platform_height + 3),
                    3.0,
                )
                .intersect(room);
            decor.fill(color.clone());
            painter
                .line(
                    center.with_z(base + platform_height + 3),
                    decor_pos.with_z(base + platform_height + 3),
                    2.0,
                )
                .intersect(decor)
                .fill(clay.clone());
        }

        // clear room
        painter
            .cylinder(Aabb {
                min: (center - (radius - 3) + 1).with_z(base + platform_height),
                max: (center + (radius - 3)).with_z(base + platform_height + height),
            })
            .clear();

        // stairs, door, windows
        for dir in CARDINALS {
            let frame_pos = center + dir * (length - 1);
            let clear_pos = center + dir * (length);

            // windows
            painter
                .line(
                    center.with_z(base + platform_height + 3),
                    frame_pos.with_z(base + platform_height + 3),
                    3.0,
                )
                .fill(color.clone());
            painter
                .line(
                    center.with_z(base + platform_height + 3),
                    clear_pos.with_z(base + platform_height + 3),
                    2.0,
                )
                .clear();
        }

        // clear the bottom bump
        painter
            .cylinder(Aabb {
                min: (center - (radius - 3)).with_z(base + platform_height),
                max: (center + (radius - 3) + 1).with_z(base + platform_height - 1),
            })
            .clear();

        // beams
        let beams_low = place_circular_as_vec(center, (2 * ((length + 6) / 3)) as f32, 5);
        let beams_high = place_circular_as_vec(center, (2 * ((length + 6) / 4)) as f32, 5);

        for b in 0..beams_low.len() {
            painter
                .line(
                    beams_low[b].with_z(base - 4),
                    beams_high[b].with_z(base + platform_height - 1),
                    1.5,
                )
                .fill(wood_dark.clone());
        }

        // floor
        painter
            .cylinder(Aabb {
                min: (center - (radius - 3)).with_z(base + platform_height),
                max: (center + (radius - 3) + 1).with_z(base + platform_height + 1),
            })
            .fill(clay.clone());

        // clear room
        painter
            .cylinder(Aabb {
                min: (center - (radius - 4) + 1).with_z(base + platform_height + 1),
                max: (center + (radius - 4)).with_z(base + platform_height + height),
            })
            .clear();

        // sprites
        painter
            .cylinder(Aabb {
                min: (center - (radius - 6)).with_z(base + platform_height + 1),
                max: (center + (radius - 6) + 1).with_z(base + platform_height + 2),
            })
            .fill(sprite_fill);

        // draws a random index
        let random_index = (RandomField::new(0).get(center.with_z(base)) % 4) as usize;
        // add bed at random diagonal
        let dir = *Dir2::ALL.get(random_index).unwrap();
        let diagonal = dir.diagonal();
        let bed_pos = center + diagonal * (length - 5);
        painter.bed_savannah(bed_pos.with_z(base + platform_height + 1), dir);

        painter
            .cylinder(Aabb {
                min: (center - (radius - 8)).with_z(base),
                max: (center + (radius - 8) + 1).with_z(base + platform_height + 2),
            })
            .clear();

        let stairs = painter.cylinder(Aabb {
            min: (center - (radius - 7)).with_z(base - 3),
            max: (center + (radius - 7) + 1).with_z(base + platform_height + 1),
        });

        stairs
            .sample(spiral_staircase(
                center.with_z(base - 3),
                (radius - 7) as f32,
                0.5,
                (platform_height + 4) as f32,
            ))
            .fill(wood_dark.clone());

        // spike
        painter
            .line(
                center.with_z(base + platform_height + 1),
                center.with_z(base + platform_height + height + (height / 2) + reed_var as i32),
                1.0,
            )
            .fill(wood_dark.clone());

        painter
            .cone(Aabb {
                min: (center - radius + 8)
                    .with_z(base + platform_height + height + (height / 2) + 2 + reed_var as i32),
                max: (center + radius - 7)
                    .with_z(base + platform_height + height + (height / 2) + 8 + reed_var as i32),
            })
            .fill(reed2.clone());
    }
}
